BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BB BBBBBBBB
                        BBB BBBBBBB BB BBBBBBBB
                            XXXX XXXXXXXXXXXX XXXXXXBB BBBBBBBBBBBB BB BBBBBBBXXXXXXBBBBBBBBBXX
                                
                            XXXXXX
                        BBBBBB
                    BBBBB

                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXX
                        XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB