BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XXXXX XXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB