BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB