BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXX XXXXXXX XXX
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBB BB BBBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBB
            XXXX XXXXXXXXXXXXX XXXXXXXX XX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXXXX
                            XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX
                                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
                                        BB BBB BBBBBBBBBBBBX BBBBB
                                    BBBBBB
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
                                    X FFFFFFFFFFF FFFFFFFFFF X
                                    BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
                                        BB BBB BBBBBBBBBBBBX BBBBB
                                    BBBBBB
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB