# Generated by Django 5.2 on 2025-05-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
