# Generated by Django 5.2 on 2025-05-19 12:42

import myprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png",
                upload_to=myprofile.models.user_avatar_path,
            ),
        ),
    ]
