# Generated by Django 5.2 on 2025-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="available_time",
            field=models.TextField(
                blank=True,
                help_text="請輸入你方便上課的時間，例如：Mon-Fri evenings, Sat morning",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="class_type",
            field=models.ManyToManyField(
                blank=True, help_text="可複選你偏好的上課型態", to="myprofile.classtype"
            ),
        ),
    ]
