# Generated by Django 5.2 on 2025-05-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_published",
            field=models.BooleanField(default=False, help_text="是否要在 category 頁面顯示"),
        ),
    ]
