# Generated by Django 5.2 on 2025-05-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instagram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
