# Generated by Django 5.2 on 2025-05-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_review'),
        ('myprofile', '0002_userprofile_city_userprofile_instagram'),
    ]

    operations = [
    ]
