# Generated by Django 5.2 on 2025-05-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0002_userprofile_city_userprofile_instagram"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="skills", to="myprofile.tag"
            ),
        ),
    ]
