# Generated by Django 5.2 on 2025-05-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0002_delete_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Skill Categories",
            },
        ),
        migrations.RemoveField(
            model_name="skill",
            name="tags",
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                default="language",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="myprofile.skillcategory",
            ),
            preserve_default=False,
        ),
    ]
