# Generated by Django 5.2 on 2025-05-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
