BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BB BBBBBBBB
                        BBB BBBBBBB BB BBBBBBBB
                            XXXX XXXXXXXXXXXX XXXXXXXX
                                
                            XXXXXX
                        BBBBBB
                    BBBBB

                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBB
                                XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                            BBBB
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                            BBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            
                            
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB