# Generated by Django 5.2 on 2025-05-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('avatar', models.ImageField(default='default.png', upload_to='mentors/')),
            ],
        ),
    ]
