# Generated by Django 5.2 on 2025-05-19 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mode', models.CharField(default='Online', max_length=50)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='myprofile.userprofile')),
            ],
        ),
    ]
