# Generated by Django 5.2 on 2025-05-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
