# Generated by Django 5.2 on 2025-05-19 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = []
