# Generated by Django 5.2 on 2025-05-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
