BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX
                        XXXXX
                    BBBB
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXX
                        XXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXX
        BBBBB BBBBBBB
        BBBBBBBB
    XXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX